### PR TITLE
fix: Gracefully handle low IPC space

### LINKED ISSUE #180: Running scip-clang inside Docker fails with 'No space left on device'
Running scip-clang v0.0.2 in the ubuntu:22.04 image leads to an error.

```
root@u18:/home/ninja# ../scip-clang --log-level=debug --compdb-path=build/compile_commands.json
[18:26:41 debug] driver    : initializing driver options
[18:26:41 debug] driver    : creating queues for IPC
[18:26:41 error] driver    : driver caught exception No space left on device
```

This problem was also reported by a customer trying out scip-clang.

It doesn't look like a read-only /dev/shm is the culprit based on findmnt.

```
/dev/shm                          shm
                                                                       tmpfs   rw,nosuid,nodev,noexec,relatime,size=65536k
```

The size of 64M, while perhaps a bit small, doesn't seem problematic; we request about (Nworkers + 1) MB of space, but the error comes up even when I  use `-j 1`.

### PR DESCRIPTION
**Pull request by varungandhi-src**
Fixes #180

### CODE REVIEW

File: indexer/Driver.cc [hunk 1]
```diff
@@ -72,18 +72,32 @@ struct MessageQueues {
 
   MessageQueues(std::string_view driverId, size_t numWorkers,
                 std::pair<size_t, size_t> elementSizes) {
+    // TODO: Get the spare memory available, maybe make this a static method,
+    // and then return either an error normally.
```
Comment (varungandhi-src) [inline indexer/Driver.cc:76]: Maybe we should just exit here if there is not enough space, because the calling code will do the same.

File: indexer/os/Linux.cc [hunk 2]
```diff
@@ -107,6 +110,20 @@ bool setCurrentThreadName(std::string_view name) {
   return retCode == 0;
 }
 
+std::variant<uint64_t, std::error_code> availableSpaceForIpc() {
+  struct statvfs shm_info;
+  // Q: Is boost/interprocess guaranteed to use /dev/shm on Linux?
+  // It seems to be the case, but I haven't yet been able to figure
+  // out where the path is decided.
```
Comment (varungandhi-src) [inline indexer/os/Linux.cc:117]: boost/interprocess used SYSV shared memory. /dev/shm seems to be guaranteed for Linux distros using glibc 2.2+ for POSIX shared memory. https://sourcegraph.com/github.com/torvalds/linux/-/blob/Documentation/filesystems/tmpfs.rst?L41-50

Can't tell if it's possible that the two don't line up in some situations...

File: indexer/os/macOS.cc [hunk 3]
```diff
@@ -74,6 +75,11 @@ bool setCurrentThreadName(std::string_view name) {
   return retCode == 0;
 }
 
+std::variant<uint64_t, std::error_code> availableSpaceForIpc() {
```
Comment (varungandhi-src) [inline indexer/os/macOS.cc:78]: Missing include for `system_error` maybe

File: indexer/JsonIpcQueue.cc [hunk 4]
```diff
@@ -14,11 +14,23 @@
...
+    }
+  }
+}
+
 char TimeoutError::ID = 0;
 
 void JsonIpcQueue::sendValue(const llvm::json::Value &jsonValue) {
   auto buffer = llvm_ext::format(jsonValue);
   this->queue->send(buffer.c_str(), buffer.size(), 1);
+  // TODO: If the buffer exceeds the size limit, we should emit an error here.
```
Comment (varungandhi-src) [inline indexer/JsonIpcQueue.cc:33]: Fix this before merging

File: indexer/Driver.cc [hunk 5]
```diff
@@ -599,7 +656,8 @@ class Driver {
         planner(this->options.projectRootPath), shardPaths(), compdbParser() {
     MessageQueues::deleteIfPresent(this->id, this->numWorkers());
     this->queues = MessageQueues(this->id, this->numWorkers(),
-                                 {IPC_BUFFER_MAX_SIZE, IPC_BUFFER_MAX_SIZE});
+                                 options.ipcOptions.ipcSizeHintBytes);
+    this->options.numWorkers = this->queues.driverToWorker.size();
```
Comment (varungandhi-src) [inline indexer/Driver.cc:660]: Maybe we should make the `numWorkers` field a stateful thing, and you need to access it using either `numWorkersHint()` and `numWorkers()`. The state would change from hint to "finalized" at this state.

Comment (varungandhi-src) [reply indexer/Driver.cc]: Let's do this in a follow-up patch...
